---

apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: openson-myapp-cicd
  namespace: tekton-builds
spec:
  params:
  - name: project
    default: myapp
  - name: release
    default: "1.0"
  workspaces:
    - name: pipeline-ws
  tasks:
  - name: build-container-image
    taskRef:
      name: build-kaniko-git
    params:
    - name: app_repo
      value: git://github.com/praveendee/$(params.project)
    - name: container_image
      value: praveendurai/$(params.project)
    - name: container_tag
      value: "$(params.release)"
  - name: deploy
    taskRef:
      name: task-kustomize
    params:
    - name: container_image
      value: praveendurai/$(params.project)
    - name: container_tag
      value: "$(params.release)"
    - name: manifests_path
      value: $(params.project)/deployment
    workspaces:
    - name: source
      workspace: pipeline-ws
    runAfter:
     - build-container-image

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-kaniko-git
  namespace: tekton-builds
spec:
  params:
  - name: app_repo
  - name: container_image
  - name: container_tag
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
      - key: .dockerconfigjson
        path: config.json
  steps:
  - name: build
    image: gcr.io/kaniko-project/executor:debug
    args:
    - --context=$(params.app_repo)
    - --destination=$(params.container_image):$(params.container_tag)
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker/

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-kustomize
  namespace: tekton-builds
spec:
  params:
  - name: container_image
    type: string
  - name: container_tag
    type: string
  - name: manifests_path
    type: string
  workspaces:
  - name: source
  steps:
  - name: version
    image: nekottyo/kustomize-kubeval
    script: |
      cd $(workspaces.source.path)/$(params.manifests_path)
      kustomize edit set image $(params.container_image)=$(params.container_image):$(params.container_tag)
      kustomize build | kubectl apply --filename -


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipelines
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines
subjects:
  - kind: ServiceAccount
    name: default
    namespace: tekton-builds
